language: node_js
node_js:
  - "0.10"
services:
  - mongodb
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - mongo mydb_test --eval 'db.addUser("bob", "test");'
  - npm start &
  - webdriver-manager update
  - webdriver-manager start &
  - sleep 3
script:
  - ./node_modules/karma/bin/karma start spec/karma.conf.js --single-run
  - ./node_modules/.bin/protractor ./spec/conf.js
