language: node_js
node_js:
- '4.1'
services:
- mongodb
addons:
  sauce_connect:
    username: dwatson62
    access_key:
      secure: hrYi43xUqFarStkoE7R08KZ3EBQVTyeNLo9Xptl5r2NpG5Oe3kTCr1S9tkZOpoPwLhJlRuNsGDTenRmJ3w7NP/dQcYArTjuG0xX1FUXyAcurlaz2rqLJtIQ2Jc01Rn1tiiIHbnkayqlfXz7gTr6rbrT4w3j/Vs8vUJfWNVP1w7P4AsxQmpc5EsU/VODqRCkF0SQh4kx0tPsrj3X8rmhnSk2jrlwYWV0OzQsD3OS9GVyMSOP7o/2NXO1OmvLlDpIx0B+Wvdkz9Ho4cEhoICOm428T+eAXL8xfV5dT6RPBxtFsYSdiX2atSG80aQwoeC2LhI8ipLNS/v9bhtycJrw2uFcptXq9fFzn/3lkcfjdGLVi5MQjdxyaT1ABqrrphbnPFKX7DwWCrQG5GOEmOT7XAJ0fzFxEO11pxzwmMDGHxONhYob0YlIHfdx0lRd7qeCnkE3PIAMGylSfv9xNVNI2R2RXJkl2RfXGujoWkBAqeZEUckNTqi3aD21JqPwgrj/AuTLJaU54kSaX/uBhf4taxT9Dc73x2w0d7DAe5ro7nbUejh+N89/KJrJvqk7sX7BRpfcae7vfVZWERTNCb4Fet57SctCyWnpbG/oQXSIAQwcoUv8Uk5ax9Myc7YcuRtXlGqBhJQhk7taA3qhC7WdoyiCx3D+ldTLVKyVLhs4WLGY=
before_script:
- sleep 15
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -g grunt-cli
- npm start &
- webdriver-manager update
- webdriver-manager start &
- sleep 3
script:
- "./node_modules/karma/bin/karma start spec/karma.conf.js --single-run"
- npm run protractor
